version: '3.7'
services:
  mysql:
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '241155'
      MYSQL_DATABASE: 'testbcpdb'
      MYSQL_USER: 'sa'
      MYSQL_PASSWORD: '123456'
    ports:
      - '3306:3306'
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge